//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.19 at 10:16:53 AM AST
//


package by.bsu.mmf.kazieva.servlet.entity.voucher;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Hotel complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Hotel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AmountOfStars" type="{http://www.example.com/students}Stars"/>
 *         &lt;element name="AmountOfRoom" type="{http://www.example.com/students}HotelRoom"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}ID">
 *             &lt;pattern value="[a-zA-Z0-9]{3,10}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="food" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="HB"/>
 *             &lt;enumeration value="BB"/>
 *             &lt;enumeration value="AL"/>
 *             &lt;enumeration value="No"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TV">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Yes"/>
 *             &lt;enumeration value="No"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="AirConditioning" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="WiFi" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hotel", propOrder = {
        "amountOfStars",
        "amountOfRoom"
})
public class Hotel {

    @XmlElement(name = "AmountOfStars", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected Integer amountOfStars;
    @XmlElement(name = "AmountOfRoom", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected Integer amountOfRoom;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String name;
    @XmlAttribute(name = "food", required = true)
    protected String food;
    @XmlAttribute(name = "TV")
    protected String tv;
    @XmlAttribute(name = "AirConditioning")
    @XmlSchemaType(name = "anySimpleType")
    protected String airConditioning;
    @XmlAttribute(name = "WiFi")
    @XmlSchemaType(name = "anySimpleType")
    protected String wiFi;

    /**
     * Gets the value of the amountOfStars property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public Integer getAmountOfStars() {
        return amountOfStars;
    }

    /**
     * Sets the value of the amountOfStars property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setAmountOfStars(Integer value) {
        this.amountOfStars = value;
    }

    /**
     * Gets the value of the amountOfRoom property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public Integer getAmountOfRoom() {
        return amountOfRoom;
    }

    /**
     * Sets the value of the amountOfRoom property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setAmountOfRoom(Integer value) {
        this.amountOfRoom = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the food property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFood() {
        return food;
    }

    /**
     * Sets the value of the food property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFood(String value) {
        this.food = value;
    }

    /**
     * Gets the value of the tv property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTV() {
        return tv;
    }

    /**
     * Sets the value of the tv property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTV(String value) {
        this.tv = value;
    }

    /**
     * Gets the value of the airConditioning property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAirConditioning() {
        return airConditioning;
    }

    /**
     * Sets the value of the airConditioning property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAirConditioning(String value) {
        this.airConditioning = value;
    }

    /**
     * Gets the value of the wiFi property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWiFi() {
        return wiFi;
    }

    /**
     * Sets the value of the wiFi property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWiFi(String value) {
        this.wiFi = value;
    }

}
