//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.19 at 10:16:53 AM AST
//


package by.bsu.mmf.kazieva.servlet.entity.voucher;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Tourist_voucher complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Tourist_voucher">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://www.example.com/students}Type"/>
 *         &lt;element name="NumberDays" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="NumberNights" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Hotel" type="{http://www.example.com/students}Hotel"/>
 *         &lt;element name="Cost" type="{http://www.example.com/students}Cost"/>
 *       &lt;/sequence>
 *       &lt;attribute name="country" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="United Kingdom"/>
 *             &lt;enumeration value="France"/>
 *             &lt;enumeration value="Denmark"/>
 *             &lt;enumeration value="Netherlands"/>
 *             &lt;enumeration value="Lithuania"/>
 *             &lt;enumeration value="Bulgaria"/>
 *             &lt;enumeration value="China"/>
 *             &lt;enumeration value="South Korea"/>
 *             &lt;enumeration value="Japan"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="transport" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Airliner"/>
 *             &lt;enumeration value="Railway"/>
 *             &lt;enumeration value="Bus"/>
 *             &lt;enumeration value="Liner"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tourist_voucher", propOrder = {
        "type",
        "numberDays",
        "numberNights",
        "hotel",
        "cost"
})
public class TouristVoucher {

    @XmlElement(name = "Type", required = true)
    @XmlSchemaType(name = "string")
    protected Type type;
    @XmlElement(name = "NumberDays", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected Integer numberDays;
    @XmlElement(name = "NumberNights", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected Integer numberNights;
    @XmlElement(name = "Hotel", required = true)
    protected Hotel hotel;
    @XmlElement(name = "Cost", required = true)
    protected Cost cost;
    @XmlAttribute(name = "country", required = true)
    protected String country;
    @XmlAttribute(name = "transport", required = true)
    protected String transport;

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link Type }
     *
     */
    public Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link Type }
     *
     */
    public void setType(Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the numberDays property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public Integer getNumberDays() {
        return numberDays;
    }

    /**
     * Sets the value of the numberDays property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setNumberDays(Integer value) {
        this.numberDays = value;
    }

    /**
     * Gets the value of the numberNights property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public Integer getNumberNights() {
        return numberNights;
    }

    /**
     * Sets the value of the numberNights property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setNumberNights(Integer value) {
        this.numberNights = value;
    }

    /**
     * Gets the value of the hotel property.
     *
     * @return
     *     possible object is
     *     {@link Hotel }
     *
     */
    public Hotel getHotel() {
        return hotel;
    }

    /**
     * Sets the value of the hotel property.
     *
     * @param value
     *     allowed object is
     *     {@link Hotel }
     *
     */
    public void setHotel(Hotel value) {
        this.hotel = value;
    }

    /**
     * Gets the value of the price property.
     *
     * @return
     *     possible object is
     *     {@link Cost }
     *
     */
    public Cost getCost() {
        return cost;
    }

    /**
     * Sets the value of the price property.
     *
     * @param value
     *     allowed object is
     *     {@link Cost }
     *
     */
    public void setCost(Cost value) {
        this.cost = value;
    }

    /**
     * Gets the value of the country property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the transport property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTransport() {
        return transport;
    }

    /**
     * Sets the value of the transport property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTransport(String value) {
        this.transport = value;
    }

}
